### ISSUE TITLE
Automatic deploy on source change is broken for Angular portlets

### ISSUE THREAD

**Issue by vincentditlevinz** [xtivia/generator-jetray#1]
There is a bug in **generators\Angular\templates\src\main\ui\gulpfile.js.blu** file. Override **webpackconfig.output.path** variable as in the code below.
(Note that one must also declare the **path** variable at the beginning of the file with something like **var path = require('path');**)

```
....
const webpackconfig = Object.create(require('./webpack.config.js'));
webpackconfig.watch = true;
webpackconfig.cache = true;
webpackconfig.bail = false;
webpackconfig.output.path = path.resolve(config.build_dir);
....
```

**Comment by mfreeman-xtivia** [comment]
I guess I would like to get some more details on what is broken?

When how/does the bug happen happen? i.e. "Automatic deploy on source change is broken .." would imply something is broken during 'gulp watch'?

**Comment by vincentditlevinz** [comment]
Yes, the path to watch is not overridden, thus the default path is used instead of the configured one.

**Comment by mfreeman-xtivia** [comment]
I tested again today, by generating an Angular portlet using Jetray with the latest version from here, and am unable to reproduce aproblem. I tested by running 'gulp watch' and then made source changes to both .ts and .html files in the application, and I see the automated deployment working just fine in the gulp window.

I guess if you really think this is a bug we may need to have you send a basic sample of what you think is a non-working test case...

**Comment by vincentditlevinz** [comment]
Maybe an IDE side effect. I use Eclipse neon. I attached a zip file of my project generated with jetray.
I noticed a comment in the generated webpack-config.js file saying: `// NOTE: path will be overridden when invoked from gulp`, that's exactly why I added `webpackconfig.output.path = path.resolve(config.build_dir);` in gulpfile.js .... and now it works for me for my IDE config.

[Project.zip](https://github.com/xtivia/generator-jetray/files/1352273/Project.zip)

**Comment by mfreeman-xtivia** [comment]
So are you running 'gulp watch' from inside of Eclipse?

**Comment by vincentditlevinz** [comment]
Yes. I open a simple "Terminal" in Eclipse, go to src/main/ui and run gulp watch.

**Comment by mfreeman-xtivia** [comment]
So I still cannot recreate this problem, even in Eclipse. Opened up a project created by jetray in Eclipse Oxygen, ran 'gulp watch' in the Terminal and everything works as expected, multiple times. I'm at a loss to understand what the issue could be...just curious what OS is this?

And if you could send me a copy of your actual generated project, I would be glad to give that a try as well...

**Comment by mfreeman-xtivia** [comment]
Shoot--so it just occurred to me when I re-read your previous comment...

Are you using the 'gradle flavor' of the generated project? I've been doing my testing with the straight-up npm flavor...

**Comment by mfreeman-xtivia** [comment]
That was it---the bug is only on the Gradle side, not the npm side. Will push in a fix.
