### ISSUE TITLE
Error: Cannot find module './simple_generator'

### ISSUE THREAD

**Issue by bkinseyx** [xtivia/generator-jetray#10]
After running `npm i -g xtivia/generator-jetray` and `yo jetray`, I got the following error:

Error: Cannot find module './simple_generator'

I checked out the install and discovered my npm dir `C:\Users\bkinsey\AppData\Roaming\npm\node_modules\generator-jetray\app` only contained index.js, not all the files I expected from `https://github.com/xtivia/generator-jetray/tree/master/app`

When I manually copied those files over from github directly, it worked.

**Comment by mfreeman-xtivia** [comment]
Incorrect directory structure was committed in 2.2 update. Addressed in commit 36216b68839bf5c782b57d373be885e413af7329
