### ISSUE TITLE
git.EXE ls-remote Error

### ISSUE THREAD

**Issue by vaasung** [xtivia/generator-jetray#2]

**Comment by vaasung** [comment]
Hi, I am getting below error while doing npm link

 C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/arobson/win-spawn.git

**Comment by mfreeman-xtivia** [comment]
No idea what you mean here. Is that the full text of the output when you run "npm link"?

**Comment by mfreeman-xtivia** [comment]
Closing issue due to lack of further response
